version: '3'

vars:
  GITVERSION:
    sh: git describe --tags --always
  GITCOMMIT:
    sh: git log -1 --pretty=format:"%H"
  BUILDDATE:
    sh: date -u '+%Y-%m-%dT%H:%M:%SZ'
  LDFLAGS:
    sh: echo "-s -w -X github.com/toolctl/toolctl/internal/cmd.gitVersion={{.GITVERSION}} -X github.com/toolctl/toolctl/internal/cmd.gitCommit={{.GITCOMMIT}} -X github.com/toolctl/toolctl/internal/cmd.buildDate={{.BUILDDATE}}"

tasks:
  build:
    desc: Build the toolctl binary
    cmds:
      - go build -ldflags "{{.LDFLAGS}}"

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  test:
    desc: Run all Go tests
    cmds:
      - go test ./...
