name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: toolctl/toolctl/.github/workflows/reusable_lint.yaml@main

  test:
    uses: toolctl/toolctl/.github/workflows/reusable_test.yaml@main
