name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Send test coverage to Code Climate
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: 570390d3fa898f29705ae8876c83d2bff6b4dd5492ea7b2fd03fce956afbc9ff
      with:
        coverageCommand: go test ./... --coverprofile c.out
