name: Lint & Test

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Set up Go
        uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # tag=v3
        with:
          go-version: '1.18'

      - name: Run the linters
        uses: golangci/golangci-lint-action@b517f99ae23d86ecc4c0dec08dcf48d2336abc29 # tag=v3.1.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Set up Go
        uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # tag=v3
        with:
          go-version: '1.18'

      - name: Run the tests and generate the coverage profile
        run: go test ./... --coverprofile=cover.out

      - name: Install gocovergate
        run: go install github.com/patrickhoefler/gocovergate@latest

      - name: Check the code coverage
        run: gocovergate
