name: Lint & Test

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Set up Go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # tag=v3
        with:
          go-version-file: 'go.mod'

      - name: Run the linters
        uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc # tag=v3.2.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Set up Go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # tag=v3
        with:
          go-version-file: 'go.mod'

      - name: Run the tests and generate the coverage profile
        run: go test ./... --coverprofile=cover.out

      - name: Install gocovergate
        run: go install github.com/patrickhoefler/gocovergate@latest

      - name: Check the code coverage
        run: gocovergate
