name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  reusable-ci:
    uses: ./.github/workflows/reusable_ci.yaml

  goreleaser:
    runs-on: ubuntu-latest
    needs: [reusable-ci]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
