name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yaml

  goreleaser:
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Set up Go
        uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # tag=v3
        with:
          go-version: '1.18'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef # tag=v3
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
